---
title: "Practice Exam - Information on every car accident in the UK 2005-15"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
#Inputs {.sidebar}
#---------------------------------------------------------
#In the following dashboard we will evaluate car accidents that occurred in the UK. Specifically, during the year 2005. Using the data set from Kaggle, https://www.kaggle.com/silicon99/dft-accident-data/data 


```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(lubridate)
```

```{r}
accidents<-read.csv("Accidents0515.csv",header=TRUE,stringsAsFactors=FALSE)

```

```{r}
df<-accidents
```

```{r}
df$Date<-dmy(df$Date)
```

```{r}
df<-df%>%
  filter(Date<="2005-12-31")
```

```{r}
df$Day_of_Week<-factor(df$Day_of_Week,levels=c("1","2","3","4","5","6","7"))
```

Column A {data-width=650}
-----------------------------------------------------------------------

### Histogram
Calculate the number of accidents occuring on each day of the week. 
Create a histogram for this.

```{r}
ggplot()+
  geom_histogram(data=df, aes(x=Day_of_Week), stat = "count", bins = 7, binwidth = 13, color="white", fill="orange")+
  ggtitle("Number of accidents occuring on each day of the week")
```

Column B {data-width=350}
-----------------------------------------------------------------------

### December Time Series 

Calculate the number of accidents occuring on each day of the year. 
```{r}
temp_df<-df%>%
  filter(Date>="2005-12-01")%>%
  group_by(Date)%>%
  summarize(acc_num=n())
```


```{r}
ggplot()+
  geom_line(data=temp_df,aes(x=Date,y=acc_num))+
  ylab("Number of Accidents")+
  scale_x_date(date_breaks='1 day',date_labels='%d')
```

Column C {data-width=350}
-----------------------------------------------------------------------

### Year Long Time Series

```{r}
temp_df<-df%>%
  group_by(Date)%>%
  summarize(acc_num=n())
```

```{r}
ggplot()+
  geom_line(data=temp_df,aes(x=Date,y=acc_num))+
  ylab("Number of Accidents")
```

